// Generated by gencpp from file arc_msgs/DropMarker.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_DROPMARKER_H
#define ARC_MSGS_MESSAGE_DROPMARKER_H

#include <ros/service_traits.h>


#include <arc_msgs/DropMarkerRequest.h>
#include <arc_msgs/DropMarkerResponse.h>


namespace arc_msgs
{

struct DropMarker
{

typedef DropMarkerRequest Request;
typedef DropMarkerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DropMarker
} // namespace arc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arc_msgs::DropMarker > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::arc_msgs::DropMarker&) { return value(); }
};

template<>
struct DataType< ::arc_msgs::DropMarker > {
  static const char* value()
  {
    return "arc_msgs/DropMarker";
  }

  static const char* value(const ::arc_msgs::DropMarker&) { return value(); }
};


// service_traits::MD5Sum< ::arc_msgs::DropMarkerRequest> should match 
// service_traits::MD5Sum< ::arc_msgs::DropMarker > 
template<>
struct MD5Sum< ::arc_msgs::DropMarkerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::DropMarker >::value();
  }
  static const char* value(const ::arc_msgs::DropMarkerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::DropMarkerRequest> should match 
// service_traits::DataType< ::arc_msgs::DropMarker > 
template<>
struct DataType< ::arc_msgs::DropMarkerRequest>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::DropMarker >::value();
  }
  static const char* value(const ::arc_msgs::DropMarkerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arc_msgs::DropMarkerResponse> should match 
// service_traits::MD5Sum< ::arc_msgs::DropMarker > 
template<>
struct MD5Sum< ::arc_msgs::DropMarkerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::DropMarker >::value();
  }
  static const char* value(const ::arc_msgs::DropMarkerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::DropMarkerResponse> should match 
// service_traits::DataType< ::arc_msgs::DropMarker > 
template<>
struct DataType< ::arc_msgs::DropMarkerResponse>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::DropMarker >::value();
  }
  static const char* value(const ::arc_msgs::DropMarkerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARC_MSGS_MESSAGE_DROPMARKER_H
