// Generated by gencpp from file arc_msgs/MoveAlterableObject.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_MOVEALTERABLEOBJECT_H
#define ARC_MSGS_MESSAGE_MOVEALTERABLEOBJECT_H

#include <ros/service_traits.h>


#include <arc_msgs/MoveAlterableObjectRequest.h>
#include <arc_msgs/MoveAlterableObjectResponse.h>


namespace arc_msgs
{

struct MoveAlterableObject
{

typedef MoveAlterableObjectRequest Request;
typedef MoveAlterableObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveAlterableObject
} // namespace arc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arc_msgs::MoveAlterableObject > {
  static const char* value()
  {
    return "7081b645962fcb4bfe66c7f0df8a9786";
  }

  static const char* value(const ::arc_msgs::MoveAlterableObject&) { return value(); }
};

template<>
struct DataType< ::arc_msgs::MoveAlterableObject > {
  static const char* value()
  {
    return "arc_msgs/MoveAlterableObject";
  }

  static const char* value(const ::arc_msgs::MoveAlterableObject&) { return value(); }
};


// service_traits::MD5Sum< ::arc_msgs::MoveAlterableObjectRequest> should match 
// service_traits::MD5Sum< ::arc_msgs::MoveAlterableObject > 
template<>
struct MD5Sum< ::arc_msgs::MoveAlterableObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::MoveAlterableObject >::value();
  }
  static const char* value(const ::arc_msgs::MoveAlterableObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::MoveAlterableObjectRequest> should match 
// service_traits::DataType< ::arc_msgs::MoveAlterableObject > 
template<>
struct DataType< ::arc_msgs::MoveAlterableObjectRequest>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::MoveAlterableObject >::value();
  }
  static const char* value(const ::arc_msgs::MoveAlterableObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arc_msgs::MoveAlterableObjectResponse> should match 
// service_traits::MD5Sum< ::arc_msgs::MoveAlterableObject > 
template<>
struct MD5Sum< ::arc_msgs::MoveAlterableObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::MoveAlterableObject >::value();
  }
  static const char* value(const ::arc_msgs::MoveAlterableObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::MoveAlterableObjectResponse> should match 
// service_traits::DataType< ::arc_msgs::MoveAlterableObject > 
template<>
struct DataType< ::arc_msgs::MoveAlterableObjectResponse>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::MoveAlterableObject >::value();
  }
  static const char* value(const ::arc_msgs::MoveAlterableObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARC_MSGS_MESSAGE_MOVEALTERABLEOBJECT_H
