// Generated by gencpp from file arc_msgs/NavigationRequestRequest.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_NAVIGATIONREQUESTREQUEST_H
#define ARC_MSGS_MESSAGE_NAVIGATIONREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace arc_msgs
{
template <class ContainerAllocator>
struct NavigationRequestRequest_
{
  typedef NavigationRequestRequest_<ContainerAllocator> Type;

  NavigationRequestRequest_()
    : priority(0)
    , pose()  {
    }
  NavigationRequestRequest_(const ContainerAllocator& _alloc)
    : priority(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _priority_type;
  _priority_type priority;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationRequestRequest_

typedef ::arc_msgs::NavigationRequestRequest_<std::allocator<void> > NavigationRequestRequest;

typedef boost::shared_ptr< ::arc_msgs::NavigationRequestRequest > NavigationRequestRequestPtr;
typedef boost::shared_ptr< ::arc_msgs::NavigationRequestRequest const> NavigationRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dynamic_reconfigure': ['/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../msg'], 'arc_msgs': ['/home/mute/workspace/arc_ws/src/arc_ros/arc_msgs/msg', '/home/mute/workspace/arc_ws/devel/share/arc_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9654db5e57f1e509ebb61644f8bd28d";
  }

  static const char* value(const ::arc_msgs::NavigationRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9654db5e57f1e50ULL;
  static const uint64_t static_value2 = 0x9ebb61644f8bd28dULL;
};

template<class ContainerAllocator>
struct DataType< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arc_msgs/NavigationRequestRequest";
  }

  static const char* value(const ::arc_msgs::NavigationRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 priority\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::arc_msgs::NavigationRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.priority);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arc_msgs::NavigationRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arc_msgs::NavigationRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "priority: ";
    Printer<int32_t>::stream(s, indent + "  ", v.priority);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARC_MSGS_MESSAGE_NAVIGATIONREQUESTREQUEST_H
