// Generated by gencpp from file arc_msgs/QuerryTaskResponse.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_QUERRYTASKRESPONSE_H
#define ARC_MSGS_MESSAGE_QUERRYTASKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arc_msgs
{
template <class ContainerAllocator>
struct QuerryTaskResponse_
{
  typedef QuerryTaskResponse_<ContainerAllocator> Type;

  QuerryTaskResponse_()
    : task_type(0)
    , priority(0)
    , bot_x(0.0)
    , bot_y(0.0)
    , loc_x(0.0)
    , loc_y(0.0)  {
    }
  QuerryTaskResponse_(const ContainerAllocator& _alloc)
    : task_type(0)
    , priority(0)
    , bot_x(0.0)
    , bot_y(0.0)
    , loc_x(0.0)
    , loc_y(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _task_type_type;
  _task_type_type task_type;

   typedef int32_t _priority_type;
  _priority_type priority;

   typedef double _bot_x_type;
  _bot_x_type bot_x;

   typedef double _bot_y_type;
  _bot_y_type bot_y;

   typedef double _loc_x_type;
  _loc_x_type loc_x;

   typedef double _loc_y_type;
  _loc_y_type loc_y;





  typedef boost::shared_ptr< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QuerryTaskResponse_

typedef ::arc_msgs::QuerryTaskResponse_<std::allocator<void> > QuerryTaskResponse;

typedef boost::shared_ptr< ::arc_msgs::QuerryTaskResponse > QuerryTaskResponsePtr;
typedef boost::shared_ptr< ::arc_msgs::QuerryTaskResponse const> QuerryTaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dynamic_reconfigure': ['/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../msg'], 'arc_msgs': ['/home/mute/workspace/arc_ws/src/arc_ros/arc_msgs/msg', '/home/mute/workspace/arc_ws/devel/share/arc_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0367c6c74ded11b47d7fe0ed3f0c4dab";
  }

  static const char* value(const ::arc_msgs::QuerryTaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0367c6c74ded11b4ULL;
  static const uint64_t static_value2 = 0x7d7fe0ed3f0c4dabULL;
};

template<class ContainerAllocator>
struct DataType< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arc_msgs/QuerryTaskResponse";
  }

  static const char* value(const ::arc_msgs::QuerryTaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 task_type\n\
int32 priority\n\
float64 bot_x\n\
float64 bot_y\n\
float64 loc_x\n\
float64 loc_y\n\
";
  }

  static const char* value(const ::arc_msgs::QuerryTaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_type);
      stream.next(m.priority);
      stream.next(m.bot_x);
      stream.next(m.bot_y);
      stream.next(m.loc_x);
      stream.next(m.loc_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuerryTaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arc_msgs::QuerryTaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arc_msgs::QuerryTaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "task_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_type);
    s << indent << "priority: ";
    Printer<int32_t>::stream(s, indent + "  ", v.priority);
    s << indent << "bot_x: ";
    Printer<double>::stream(s, indent + "  ", v.bot_x);
    s << indent << "bot_y: ";
    Printer<double>::stream(s, indent + "  ", v.bot_y);
    s << indent << "loc_x: ";
    Printer<double>::stream(s, indent + "  ", v.loc_x);
    s << indent << "loc_y: ";
    Printer<double>::stream(s, indent + "  ", v.loc_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARC_MSGS_MESSAGE_QUERRYTASKRESPONSE_H
