// Generated by gencpp from file arc_msgs/QuerryRoleResponse.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_QUERRYROLERESPONSE_H
#define ARC_MSGS_MESSAGE_QUERRYROLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arc_msgs
{
template <class ContainerAllocator>
struct QuerryRoleResponse_
{
  typedef QuerryRoleResponse_<ContainerAllocator> Type;

  QuerryRoleResponse_()
    : app(0.0)  {
    }
  QuerryRoleResponse_(const ContainerAllocator& _alloc)
    : app(0.0)  {
  (void)_alloc;
    }



   typedef float _app_type;
  _app_type app;





  typedef boost::shared_ptr< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QuerryRoleResponse_

typedef ::arc_msgs::QuerryRoleResponse_<std::allocator<void> > QuerryRoleResponse;

typedef boost::shared_ptr< ::arc_msgs::QuerryRoleResponse > QuerryRoleResponsePtr;
typedef boost::shared_ptr< ::arc_msgs::QuerryRoleResponse const> QuerryRoleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dynamic_reconfigure': ['/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../msg'], 'arc_msgs': ['/home/mute/workspace/arc_ws/src/arc_ros/arc_msgs/msg', '/home/mute/workspace/arc_ws/devel/share/arc_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88d6aa86935cc331b7d45537a5e7011f";
  }

  static const char* value(const ::arc_msgs::QuerryRoleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88d6aa86935cc331ULL;
  static const uint64_t static_value2 = 0xb7d45537a5e7011fULL;
};

template<class ContainerAllocator>
struct DataType< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arc_msgs/QuerryRoleResponse";
  }

  static const char* value(const ::arc_msgs::QuerryRoleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 app\n\
\n\
";
  }

  static const char* value(const ::arc_msgs::QuerryRoleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.app);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuerryRoleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arc_msgs::QuerryRoleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arc_msgs::QuerryRoleResponse_<ContainerAllocator>& v)
  {
    s << indent << "app: ";
    Printer<float>::stream(s, indent + "  ", v.app);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARC_MSGS_MESSAGE_QUERRYROLERESPONSE_H
