// Generated by gencpp from file arc_msgs/QuerryRole.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_QUERRYROLE_H
#define ARC_MSGS_MESSAGE_QUERRYROLE_H

#include <ros/service_traits.h>


#include <arc_msgs/QuerryRoleRequest.h>
#include <arc_msgs/QuerryRoleResponse.h>


namespace arc_msgs
{

struct QuerryRole
{

typedef QuerryRoleRequest Request;
typedef QuerryRoleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QuerryRole
} // namespace arc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arc_msgs::QuerryRole > {
  static const char* value()
  {
    return "d7615da21ebfea9eb2a1d406fa324a4c";
  }

  static const char* value(const ::arc_msgs::QuerryRole&) { return value(); }
};

template<>
struct DataType< ::arc_msgs::QuerryRole > {
  static const char* value()
  {
    return "arc_msgs/QuerryRole";
  }

  static const char* value(const ::arc_msgs::QuerryRole&) { return value(); }
};


// service_traits::MD5Sum< ::arc_msgs::QuerryRoleRequest> should match 
// service_traits::MD5Sum< ::arc_msgs::QuerryRole > 
template<>
struct MD5Sum< ::arc_msgs::QuerryRoleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::QuerryRole >::value();
  }
  static const char* value(const ::arc_msgs::QuerryRoleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::QuerryRoleRequest> should match 
// service_traits::DataType< ::arc_msgs::QuerryRole > 
template<>
struct DataType< ::arc_msgs::QuerryRoleRequest>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::QuerryRole >::value();
  }
  static const char* value(const ::arc_msgs::QuerryRoleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arc_msgs::QuerryRoleResponse> should match 
// service_traits::MD5Sum< ::arc_msgs::QuerryRole > 
template<>
struct MD5Sum< ::arc_msgs::QuerryRoleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::QuerryRole >::value();
  }
  static const char* value(const ::arc_msgs::QuerryRoleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::QuerryRoleResponse> should match 
// service_traits::DataType< ::arc_msgs::QuerryRole > 
template<>
struct DataType< ::arc_msgs::QuerryRoleResponse>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::QuerryRole >::value();
  }
  static const char* value(const ::arc_msgs::QuerryRoleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARC_MSGS_MESSAGE_QUERRYROLE_H
