// Generated by gencpp from file arc_msgs/QuerryTask.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_QUERRYTASK_H
#define ARC_MSGS_MESSAGE_QUERRYTASK_H

#include <ros/service_traits.h>


#include <arc_msgs/QuerryTaskRequest.h>
#include <arc_msgs/QuerryTaskResponse.h>


namespace arc_msgs
{

struct QuerryTask
{

typedef QuerryTaskRequest Request;
typedef QuerryTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QuerryTask
} // namespace arc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arc_msgs::QuerryTask > {
  static const char* value()
  {
    return "0367c6c74ded11b47d7fe0ed3f0c4dab";
  }

  static const char* value(const ::arc_msgs::QuerryTask&) { return value(); }
};

template<>
struct DataType< ::arc_msgs::QuerryTask > {
  static const char* value()
  {
    return "arc_msgs/QuerryTask";
  }

  static const char* value(const ::arc_msgs::QuerryTask&) { return value(); }
};


// service_traits::MD5Sum< ::arc_msgs::QuerryTaskRequest> should match 
// service_traits::MD5Sum< ::arc_msgs::QuerryTask > 
template<>
struct MD5Sum< ::arc_msgs::QuerryTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::QuerryTask >::value();
  }
  static const char* value(const ::arc_msgs::QuerryTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::QuerryTaskRequest> should match 
// service_traits::DataType< ::arc_msgs::QuerryTask > 
template<>
struct DataType< ::arc_msgs::QuerryTaskRequest>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::QuerryTask >::value();
  }
  static const char* value(const ::arc_msgs::QuerryTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arc_msgs::QuerryTaskResponse> should match 
// service_traits::MD5Sum< ::arc_msgs::QuerryTask > 
template<>
struct MD5Sum< ::arc_msgs::QuerryTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::QuerryTask >::value();
  }
  static const char* value(const ::arc_msgs::QuerryTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::QuerryTaskResponse> should match 
// service_traits::DataType< ::arc_msgs::QuerryTask > 
template<>
struct DataType< ::arc_msgs::QuerryTaskResponse>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::QuerryTask >::value();
  }
  static const char* value(const ::arc_msgs::QuerryTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARC_MSGS_MESSAGE_QUERRYTASK_H
