// Generated by gencpp from file arc_msgs/TaskResponse.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_TASKRESPONSE_H
#define ARC_MSGS_MESSAGE_TASKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arc_msgs
{
template <class ContainerAllocator>
struct TaskResponse_
{
  typedef TaskResponse_<ContainerAllocator> Type;

  TaskResponse_()
    : accepted(0)  {
    }
  TaskResponse_(const ContainerAllocator& _alloc)
    : accepted(0)  {
  (void)_alloc;
    }



   typedef int32_t _accepted_type;
  _accepted_type accepted;





  typedef boost::shared_ptr< ::arc_msgs::TaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arc_msgs::TaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TaskResponse_

typedef ::arc_msgs::TaskResponse_<std::allocator<void> > TaskResponse;

typedef boost::shared_ptr< ::arc_msgs::TaskResponse > TaskResponsePtr;
typedef boost::shared_ptr< ::arc_msgs::TaskResponse const> TaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arc_msgs::TaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arc_msgs::TaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dynamic_reconfigure': ['/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../msg'], 'arc_msgs': ['/home/mute/workspace/arc_ws/src/arc_ros/arc_msgs/msg', '/home/mute/workspace/arc_ws/devel/share/arc_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::TaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::TaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::TaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::TaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::TaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::TaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arc_msgs::TaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "430740ff278410c65f142021b3dd13fe";
  }

  static const char* value(const ::arc_msgs::TaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x430740ff278410c6ULL;
  static const uint64_t static_value2 = 0x5f142021b3dd13feULL;
};

template<class ContainerAllocator>
struct DataType< ::arc_msgs::TaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arc_msgs/TaskResponse";
  }

  static const char* value(const ::arc_msgs::TaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arc_msgs::TaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 accepted\n\
";
  }

  static const char* value(const ::arc_msgs::TaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arc_msgs::TaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arc_msgs::TaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arc_msgs::TaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "accepted: ";
    Printer<int32_t>::stream(s, indent + "  ", v.accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARC_MSGS_MESSAGE_TASKRESPONSE_H
