// Generated by gencpp from file arc_msgs/Task.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_TASK_H
#define ARC_MSGS_MESSAGE_TASK_H

#include <ros/service_traits.h>


#include <arc_msgs/TaskRequest.h>
#include <arc_msgs/TaskResponse.h>


namespace arc_msgs
{

struct Task
{

typedef TaskRequest Request;
typedef TaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Task
} // namespace arc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arc_msgs::Task > {
  static const char* value()
  {
    return "b4cba0104ef3e5618ceceb1e9c5f477f";
  }

  static const char* value(const ::arc_msgs::Task&) { return value(); }
};

template<>
struct DataType< ::arc_msgs::Task > {
  static const char* value()
  {
    return "arc_msgs/Task";
  }

  static const char* value(const ::arc_msgs::Task&) { return value(); }
};


// service_traits::MD5Sum< ::arc_msgs::TaskRequest> should match 
// service_traits::MD5Sum< ::arc_msgs::Task > 
template<>
struct MD5Sum< ::arc_msgs::TaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::Task >::value();
  }
  static const char* value(const ::arc_msgs::TaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::TaskRequest> should match 
// service_traits::DataType< ::arc_msgs::Task > 
template<>
struct DataType< ::arc_msgs::TaskRequest>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::Task >::value();
  }
  static const char* value(const ::arc_msgs::TaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arc_msgs::TaskResponse> should match 
// service_traits::MD5Sum< ::arc_msgs::Task > 
template<>
struct MD5Sum< ::arc_msgs::TaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::Task >::value();
  }
  static const char* value(const ::arc_msgs::TaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::TaskResponse> should match 
// service_traits::DataType< ::arc_msgs::Task > 
template<>
struct DataType< ::arc_msgs::TaskResponse>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::Task >::value();
  }
  static const char* value(const ::arc_msgs::TaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARC_MSGS_MESSAGE_TASK_H
