// Generated by gencpp from file arc_msgs/ToggleSchema.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_TOGGLESCHEMA_H
#define ARC_MSGS_MESSAGE_TOGGLESCHEMA_H

#include <ros/service_traits.h>


#include <arc_msgs/ToggleSchemaRequest.h>
#include <arc_msgs/ToggleSchemaResponse.h>


namespace arc_msgs
{

struct ToggleSchema
{

typedef ToggleSchemaRequest Request;
typedef ToggleSchemaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleSchema
} // namespace arc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arc_msgs::ToggleSchema > {
  static const char* value()
  {
    return "8ef993123e0d3a927ec9795e9c47782f";
  }

  static const char* value(const ::arc_msgs::ToggleSchema&) { return value(); }
};

template<>
struct DataType< ::arc_msgs::ToggleSchema > {
  static const char* value()
  {
    return "arc_msgs/ToggleSchema";
  }

  static const char* value(const ::arc_msgs::ToggleSchema&) { return value(); }
};


// service_traits::MD5Sum< ::arc_msgs::ToggleSchemaRequest> should match 
// service_traits::MD5Sum< ::arc_msgs::ToggleSchema > 
template<>
struct MD5Sum< ::arc_msgs::ToggleSchemaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::ToggleSchema >::value();
  }
  static const char* value(const ::arc_msgs::ToggleSchemaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::ToggleSchemaRequest> should match 
// service_traits::DataType< ::arc_msgs::ToggleSchema > 
template<>
struct DataType< ::arc_msgs::ToggleSchemaRequest>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::ToggleSchema >::value();
  }
  static const char* value(const ::arc_msgs::ToggleSchemaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arc_msgs::ToggleSchemaResponse> should match 
// service_traits::MD5Sum< ::arc_msgs::ToggleSchema > 
template<>
struct MD5Sum< ::arc_msgs::ToggleSchemaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::ToggleSchema >::value();
  }
  static const char* value(const ::arc_msgs::ToggleSchemaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::ToggleSchemaResponse> should match 
// service_traits::DataType< ::arc_msgs::ToggleSchema > 
template<>
struct DataType< ::arc_msgs::ToggleSchemaResponse>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::ToggleSchema >::value();
  }
  static const char* value(const ::arc_msgs::ToggleSchemaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARC_MSGS_MESSAGE_TOGGLESCHEMA_H
