// Generated by gencpp from file arc_msgs/ToggleListRequest.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_TOGGLELISTREQUEST_H
#define ARC_MSGS_MESSAGE_TOGGLELISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arc_msgs
{
template <class ContainerAllocator>
struct ToggleListRequest_
{
  typedef ToggleListRequest_<ContainerAllocator> Type;

  ToggleListRequest_()
    : random_wander(false)
    , move_to_goal(false)
    , clean_debris(false)
    , detect_debris(false)  {
    }
  ToggleListRequest_(const ContainerAllocator& _alloc)
    : random_wander(false)
    , move_to_goal(false)
    , clean_debris(false)
    , detect_debris(false)  {
  (void)_alloc;
    }



   typedef uint8_t _random_wander_type;
  _random_wander_type random_wander;

   typedef uint8_t _move_to_goal_type;
  _move_to_goal_type move_to_goal;

   typedef uint8_t _clean_debris_type;
  _clean_debris_type clean_debris;

   typedef uint8_t _detect_debris_type;
  _detect_debris_type detect_debris;





  typedef boost::shared_ptr< ::arc_msgs::ToggleListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arc_msgs::ToggleListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleListRequest_

typedef ::arc_msgs::ToggleListRequest_<std::allocator<void> > ToggleListRequest;

typedef boost::shared_ptr< ::arc_msgs::ToggleListRequest > ToggleListRequestPtr;
typedef boost::shared_ptr< ::arc_msgs::ToggleListRequest const> ToggleListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arc_msgs::ToggleListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dynamic_reconfigure': ['/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../msg'], 'arc_msgs': ['/home/mute/workspace/arc_ws/src/arc_ros/arc_msgs/msg', '/home/mute/workspace/arc_ws/devel/share/arc_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::ToggleListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::ToggleListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::ToggleListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc98542f37cff10cf2b272c02d421986";
  }

  static const char* value(const ::arc_msgs::ToggleListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc98542f37cff10cULL;
  static const uint64_t static_value2 = 0xf2b272c02d421986ULL;
};

template<class ContainerAllocator>
struct DataType< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arc_msgs/ToggleListRequest";
  }

  static const char* value(const ::arc_msgs::ToggleListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool random_wander\n\
bool move_to_goal\n\
bool clean_debris\n\
bool detect_debris\n\
";
  }

  static const char* value(const ::arc_msgs::ToggleListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.random_wander);
      stream.next(m.move_to_goal);
      stream.next(m.clean_debris);
      stream.next(m.detect_debris);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arc_msgs::ToggleListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arc_msgs::ToggleListRequest_<ContainerAllocator>& v)
  {
    s << indent << "random_wander: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.random_wander);
    s << indent << "move_to_goal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.move_to_goal);
    s << indent << "clean_debris: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clean_debris);
    s << indent << "detect_debris: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detect_debris);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARC_MSGS_MESSAGE_TOGGLELISTREQUEST_H
