// Generated by gencpp from file arc_msgs/ToggleSchemaRequest.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_TOGGLESCHEMAREQUEST_H
#define ARC_MSGS_MESSAGE_TOGGLESCHEMAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dynamic_reconfigure/BoolParameter.h>

namespace arc_msgs
{
template <class ContainerAllocator>
struct ToggleSchemaRequest_
{
  typedef ToggleSchemaRequest_<ContainerAllocator> Type;

  ToggleSchemaRequest_()
    : schema()  {
    }
  ToggleSchemaRequest_(const ContainerAllocator& _alloc)
    : schema(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::dynamic_reconfigure::BoolParameter_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dynamic_reconfigure::BoolParameter_<ContainerAllocator> >::other >  _schema_type;
  _schema_type schema;





  typedef boost::shared_ptr< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleSchemaRequest_

typedef ::arc_msgs::ToggleSchemaRequest_<std::allocator<void> > ToggleSchemaRequest;

typedef boost::shared_ptr< ::arc_msgs::ToggleSchemaRequest > ToggleSchemaRequestPtr;
typedef boost::shared_ptr< ::arc_msgs::ToggleSchemaRequest const> ToggleSchemaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'dynamic_reconfigure': ['/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../msg'], 'arc_msgs': ['/home/mute/workspace/arc_ws/src/arc_ros/arc_msgs/msg', '/home/mute/workspace/arc_ws/devel/share/arc_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7710a5d0d41dc5dfbfa6fdd0dd796270";
  }

  static const char* value(const ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7710a5d0d41dc5dfULL;
  static const uint64_t static_value2 = 0xbfa6fdd0dd796270ULL;
};

template<class ContainerAllocator>
struct DataType< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arc_msgs/ToggleSchemaRequest";
  }

  static const char* value(const ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
dynamic_reconfigure/BoolParameter[] schema\n\
\n\
================================================================================\n\
MSG: dynamic_reconfigure/BoolParameter\n\
string name\n\
bool value\n\
";
  }

  static const char* value(const ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.schema);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleSchemaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arc_msgs::ToggleSchemaRequest_<ContainerAllocator>& v)
  {
    s << indent << "schema[]" << std::endl;
    for (size_t i = 0; i < v.schema.size(); ++i)
    {
      s << indent << "  schema[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dynamic_reconfigure::BoolParameter_<ContainerAllocator> >::stream(s, indent + "    ", v.schema[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARC_MSGS_MESSAGE_TOGGLESCHEMAREQUEST_H
