// Generated by gencpp from file arc_msgs/ToggleList.msg
// DO NOT EDIT!


#ifndef ARC_MSGS_MESSAGE_TOGGLELIST_H
#define ARC_MSGS_MESSAGE_TOGGLELIST_H

#include <ros/service_traits.h>


#include <arc_msgs/ToggleListRequest.h>
#include <arc_msgs/ToggleListResponse.h>


namespace arc_msgs
{

struct ToggleList
{

typedef ToggleListRequest Request;
typedef ToggleListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleList
} // namespace arc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arc_msgs::ToggleList > {
  static const char* value()
  {
    return "fc98542f37cff10cf2b272c02d421986";
  }

  static const char* value(const ::arc_msgs::ToggleList&) { return value(); }
};

template<>
struct DataType< ::arc_msgs::ToggleList > {
  static const char* value()
  {
    return "arc_msgs/ToggleList";
  }

  static const char* value(const ::arc_msgs::ToggleList&) { return value(); }
};


// service_traits::MD5Sum< ::arc_msgs::ToggleListRequest> should match 
// service_traits::MD5Sum< ::arc_msgs::ToggleList > 
template<>
struct MD5Sum< ::arc_msgs::ToggleListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::ToggleList >::value();
  }
  static const char* value(const ::arc_msgs::ToggleListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::ToggleListRequest> should match 
// service_traits::DataType< ::arc_msgs::ToggleList > 
template<>
struct DataType< ::arc_msgs::ToggleListRequest>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::ToggleList >::value();
  }
  static const char* value(const ::arc_msgs::ToggleListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arc_msgs::ToggleListResponse> should match 
// service_traits::MD5Sum< ::arc_msgs::ToggleList > 
template<>
struct MD5Sum< ::arc_msgs::ToggleListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arc_msgs::ToggleList >::value();
  }
  static const char* value(const ::arc_msgs::ToggleListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arc_msgs::ToggleListResponse> should match 
// service_traits::DataType< ::arc_msgs::ToggleList > 
template<>
struct DataType< ::arc_msgs::ToggleListResponse>
{
  static const char* value()
  {
    return DataType< ::arc_msgs::ToggleList >::value();
  }
  static const char* value(const ::arc_msgs::ToggleListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARC_MSGS_MESSAGE_TOGGLELIST_H
